/**
 * Surah names and revelation place, following Tanzil's quran-data metadata
 * (https://tanzil.net/res/text/metadata/quran-data.js). The corpus file
 * carries no chapter names, so this is the one hand-maintained table in the
 * Qur'an pipeline; verse counts are deliberately NOT stored here — the
 * importer derives them from the corpus itself, so they can't drift.
 */

export interface ChapterMeta {
  id: number;
  nameAr: string;
  nameTransliteration: string;
  nameEn: string;
  revelationPlace: "meccan" | "medinan";
}

type Row = [nameAr: string, nameTransliteration: string, nameEn: string];

const ROWS: Row[] = [
  ["الفاتحة", "Al-Faatiha", "The Opening"],
  ["البقرة", "Al-Baqara", "The Cow"],
  ["آل عمران", "Aal-i-Imraan", "The Family of Imraan"],
  ["النساء", "An-Nisaa", "The Women"],
  ["المائدة", "Al-Maaida", "The Table"],
  ["الأنعام", "Al-An'aam", "The Cattle"],
  ["الأعراف", "Al-A'raaf", "The Heights"],
  ["الأنفال", "Al-Anfaal", "The Spoils of War"],
  ["التوبة", "At-Tawba", "The Repentance"],
  ["يونس", "Yunus", "Jonas"],
  ["هود", "Hud", "Hud"],
  ["يوسف", "Yusuf", "Joseph"],
  ["الرعد", "Ar-Ra'd", "The Thunder"],
  ["ابراهيم", "Ibrahim", "Abraham"],
  ["الحجر", "Al-Hijr", "The Rock"],
  ["النحل", "An-Nahl", "The Bee"],
  ["الإسراء", "Al-Israa", "The Night Journey"],
  ["الكهف", "Al-Kahf", "The Cave"],
  ["مريم", "Maryam", "Mary"],
  ["طه", "Taa-Haa", "Taa-Haa"],
  ["الأنبياء", "Al-Anbiyaa", "The Prophets"],
  ["الحج", "Al-Hajj", "The Pilgrimage"],
  ["المؤمنون", "Al-Muminoon", "The Believers"],
  ["النور", "An-Noor", "The Light"],
  ["الفرقان", "Al-Furqaan", "The Criterion"],
  ["الشعراء", "Ash-Shu'araa", "The Poets"],
  ["النمل", "An-Naml", "The Ant"],
  ["القصص", "Al-Qasas", "The Stories"],
  ["العنكبوت", "Al-Ankaboot", "The Spider"],
  ["الروم", "Ar-Room", "The Romans"],
  ["لقمان", "Luqman", "Luqman"],
  ["السجدة", "As-Sajda", "The Prostration"],
  ["الأحزاب", "Al-Ahzaab", "The Clans"],
  ["سبإ", "Saba", "Sheba"],
  ["فاطر", "Faatir", "The Originator"],
  ["يس", "Yaseen", "Yaseen"],
  ["الصافات", "As-Saaffaat", "Those drawn up in Ranks"],
  ["ص", "Saad", "The letter Saad"],
  ["الزمر", "Az-Zumar", "The Groups"],
  ["غافر", "Ghafir", "The Forgiver"],
  ["فصلت", "Fussilat", "Explained in detail"],
  ["الشورى", "Ash-Shura", "Consultation"],
  ["الزخرف", "Az-Zukhruf", "Ornaments of gold"],
  ["الدخان", "Ad-Dukhaan", "The Smoke"],
  ["الجاثية", "Al-Jaathiya", "Crouching"],
  ["الأحقاف", "Al-Ahqaf", "The Dunes"],
  ["محمد", "Muhammad", "Muhammad"],
  ["الفتح", "Al-Fath", "The Victory"],
  ["الحجرات", "Al-Hujuraat", "The Inner Apartments"],
  ["ق", "Qaaf", "The letter Qaaf"],
  ["الذاريات", "Adh-Dhaariyat", "The Winnowing Winds"],
  ["الطور", "At-Tur", "The Mount"],
  ["النجم", "An-Najm", "The Star"],
  ["القمر", "Al-Qamar", "The Moon"],
  ["الرحمن", "Ar-Rahmaan", "The Beneficent"],
  ["الواقعة", "Al-Waaqia", "The Inevitable"],
  ["الحديد", "Al-Hadid", "The Iron"],
  ["المجادلة", "Al-Mujaadila", "The Pleading Woman"],
  ["الحشر", "Al-Hashr", "The Exile"],
  ["الممتحنة", "Al-Mumtahana", "She that is to be examined"],
  ["الصف", "As-Saff", "The Ranks"],
  ["الجمعة", "Al-Jumu'a", "Friday"],
  ["المنافقون", "Al-Munaafiqoon", "The Hypocrites"],
  ["التغابن", "At-Taghaabun", "Mutual Disillusion"],
  ["الطلاق", "At-Talaaq", "Divorce"],
  ["التحريم", "At-Tahrim", "The Prohibition"],
  ["الملك", "Al-Mulk", "The Sovereignty"],
  ["القلم", "Al-Qalam", "The Pen"],
  ["الحاقة", "Al-Haaqqa", "The Reality"],
  ["المعارج", "Al-Ma'aarij", "The Ascending Stairways"],
  ["نوح", "Nooh", "Noah"],
  ["الجن", "Al-Jinn", "The Jinn"],
  ["المزمل", "Al-Muzzammil", "The Enshrouded One"],
  ["المدثر", "Al-Muddaththir", "The Cloaked One"],
  ["القيامة", "Al-Qiyaama", "The Resurrection"],
  ["الانسان", "Al-Insaan", "Man"],
  ["المرسلات", "Al-Mursalaat", "The Emissaries"],
  ["النبإ", "An-Naba", "The Announcement"],
  ["النازعات", "An-Naazi'aat", "Those who drag forth"],
  ["عبس", "Abasa", "He frowned"],
  ["التكوير", "At-Takwir", "The Overthrowing"],
  ["الإنفطار", "Al-Infitaar", "The Cleaving"],
  ["المطففين", "Al-Mutaffifin", "Defrauding"],
  ["الإنشقاق", "Al-Inshiqaaq", "The Splitting Open"],
  ["البروج", "Al-Burooj", "The Constellations"],
  ["الطارق", "At-Taariq", "The Morning Star"],
  ["الأعلى", "Al-A'laa", "The Most High"],
  ["الغاشية", "Al-Ghaashiya", "The Overwhelming"],
  ["الفجر", "Al-Fajr", "The Dawn"],
  ["البلد", "Al-Balad", "The City"],
  ["الشمس", "Ash-Shams", "The Sun"],
  ["الليل", "Al-Lail", "The Night"],
  ["الضحى", "Ad-Dhuhaa", "The Morning Hours"],
  ["الشرح", "Ash-Sharh", "The Consolation"],
  ["التين", "At-Tin", "The Fig"],
  ["العلق", "Al-Alaq", "The Clot"],
  ["القدر", "Al-Qadr", "The Power, Fate"],
  ["البينة", "Al-Bayyina", "The Evidence"],
  ["الزلزلة", "Az-Zalzala", "The Earthquake"],
  ["العاديات", "Al-Aadiyaat", "The Chargers"],
  ["القارعة", "Al-Qaari'a", "The Calamity"],
  ["التكاثر", "At-Takaathur", "Competition"],
  ["العصر", "Al-Asr", "The Declining Day, Epoch"],
  ["الهمزة", "Al-Humaza", "The Traducer"],
  ["الفيل", "Al-Fil", "The Elephant"],
  ["قريش", "Quraish", "Quraysh"],
  ["الماعون", "Al-Maa'un", "Almsgiving"],
  ["الكوثر", "Al-Kawthar", "Abundance"],
  ["الكافرون", "Al-Kaafiroon", "The Disbelievers"],
  ["النصر", "An-Nasr", "Divine Support"],
  ["المسد", "Al-Masad", "The Palm Fibre"],
  ["الإخلاص", "Al-Ikhlaas", "Sincerity"],
  ["الفلق", "Al-Falaq", "The Dawn"],
  ["الناس", "An-Naas", "Mankind"],
];

/** Tanzil's Medinan classification; every other surah is Meccan. */
const MEDINAN = new Set([2, 3, 4, 5, 8, 9, 13, 22, 24, 33, 47, 48, 49, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76, 98, 99, 110]);

export const CHAPTERS: ChapterMeta[] = ROWS.map(([nameAr, nameTransliteration, nameEn], i) => ({
  id: i + 1,
  nameAr,
  nameTransliteration,
  nameEn,
  revelationPlace: MEDINAN.has(i + 1) ? "medinan" : "meccan",
}));
