/**
 * Accuracy gold set: fully vowelled textbook sentences with their correct
 * i'rab, one entry per typed word. A word split into pieces (بِ + القَلَمِ,
 * كَتَبَ + ـهُ) lists its pieces' roles joined by "+", in reading order.
 * "X" marks a word whose correct role isn't one the parser has (مفعول لأجله،
 * منادى، توكيد، أداة استفهام…): the only right answer there is a refusal.
 *
 * The set deliberately includes constructions outside the parser's
 * coverage — the report (npm run irab:accuracy) measures how often the
 * parser is *wrong*, which must be never, and how often it declines.
 */
export const GOLD: [sentence: string, roles: string][] = [
  // --- verbal sentences
  ["قَرَأَ الطَّالِبُ الكِتَابَ", "FIL FAAIL MAFUL_BIH"],
  ["فَتَحَ الوَلَدُ البَابَ", "FIL FAAIL MAFUL_BIH"],
  ["شَرِبَ الطِّفْلُ الحَلِيبَ", "FIL FAAIL MAFUL_BIH"],
  ["جَلَسَ المُعَلِّمُ عَلَى الكُرْسِيِّ", "FIL FAAIL HARF_JARR MAJROOR"],
  ["خَرَجَ الرَّجُلُ مِنَ البَيْتِ", "FIL FAAIL HARF_JARR MAJROOR"],
  ["يَقْرَأُ الطَّالِبُ الدَّرْسَ", "FIL FAAIL MAFUL_BIH"],
  ["تَكْتُبُ البِنْتُ الرِّسَالَةَ", "FIL FAAIL MAFUL_BIH"],
  ["نَصَرَ اللهُ المُؤْمِنِينَ", "FIL FAAIL MAFUL_BIH"],
  ["سَمِعْتُ الأَذَانَ", "FIL MAFUL_BIH"],
  ["فَهِمْنَا الدَّرْسَ", "FIL MAFUL_BIH"],
  ["حَفِظَ الطُّلَّابُ القُرْآنَ", "FIL FAAIL MAFUL_BIH"],
  ["رَجَعَ المُسَافِرُ إِلَى بَلَدِهِ", "FIL FAAIL HARF_JARR MAJROOR+MUDAF_ILAYH"],
  ["أَكَلَ الوَلَدُ التُّفَّاحَةَ", "FIL FAAIL MAFUL_BIH"],
  ["يَلْعَبُ الأَطْفَالُ فِي الحَدِيقَةِ", "FIL FAAIL HARF_JARR MAJROOR"],
  ["كَتَبَتِ الطَّالِبَةُ الوَاجِبَ", "FIL FAAIL MAFUL_BIH"],
  ["نَامَ الطِّفْلُ", "FIL FAAIL"],
  ["طَلَعَتِ الشَّمْسُ", "FIL FAAIL"],
  ["يَذْهَبُونَ إِلَى المَسْجِدِ", "FIL HARF_JARR MAJROOR"],
  ["اِفْتَحِ البَابَ", "FIL MAFUL_BIH"],
  ["سُرِقَ المَالُ", "FIL NAIB_FAAIL"],
  ["فُتِحَ البَابُ", "FIL NAIB_FAAIL"],
  ["يُكْرَمُ الضَّيْفُ", "FIL NAIB_FAAIL"],
  ["أَرْسَلْتُ رِسَالَةً إِلَى صَدِيقِي", "FIL MAFUL_BIH HARF_JARR MAJROOR+MUDAF_ILAYH"],
  ["قَابَلْتُ المُدِيرَ", "FIL MAFUL_BIH"],
  ["سَافَرَ أَخِي", "FIL FAAIL+MUDAF_ILAYH"],
  ["جَاءَ أَخُو زَيْدٍ", "FIL FAAIL MUDAF_ILAYH"],
  ["رَأَيْتُ أَبَاكَ", "FIL MAFUL_BIH+MUDAF_ILAYH"],
  ["سَلَّمْتُ عَلَى أَبِيكَ", "FIL HARF_JARR MAJROOR+MUDAF_ILAYH"],
  ["عَادَ المُسَافِرُونَ", "FIL FAAIL"],
  ["رَأَيْتُ المُهَنْدِسِينَ", "FIL MAFUL_BIH"],
  ["سَلَّمْتُ عَلَى المُعَلِّمَيْنِ", "FIL HARF_JARR MAJROOR"],
  ["حَضَرَ الطَّالِبَانِ", "FIL FAAIL"],
  ["شَاهَدْتُ الطَّالِبَاتِ", "FIL MAFUL_BIH"],

  // --- nominal sentences
  ["العِلْمُ نُورٌ", "MUBTADA KHABAR"],
  ["البَيْتُ كَبِيرٌ", "MUBTADA KHABAR"],
  ["الشَّمْسُ طَالِعَةٌ", "MUBTADA KHABAR"],
  ["المُسْلِمُونَ صَادِقُونَ", "MUBTADA KHABAR"],
  ["الطَّالِبَانِ مُجْتَهِدَانِ", "MUBTADA KHABAR"],
  ["المُعَلِّمَاتُ حَاضِرَاتٌ", "MUBTADA KHABAR"],
  ["الطَّالِبَاتُ مُجْتَهِدَاتٌ", "MUBTADA KHABAR"],
  ["أَنَا طَالِبٌ", "MUBTADA KHABAR"],
  ["نَحْنُ مُسْلِمُونَ", "MUBTADA KHABAR"],
  ["هِيَ مُعَلِّمَةٌ", "MUBTADA KHABAR"],
  ["هَذِهِ مَدْرَسَةٌ", "MUBTADA KHABAR"],
  ["هَذَا بَيْتٌ جَمِيلٌ", "MUBTADA KHABAR NAAT"],
  ["الكِتَابُ عَلَى المَكْتَبِ", "MUBTADA HARF_JARR MAJROOR"],
  ["الطَّالِبُ فِي الفَصْلِ", "MUBTADA HARF_JARR MAJROOR"],
  ["فِي المَسْجِدِ رِجَالٌ", "HARF_JARR MAJROOR MUBTADA"],
  ["لِلطَّالِبِ كِتَابٌ", "HARF_JARR+MAJROOR MUBTADA"],
  ["زَيْدٌ قَائِمٌ", "MUBTADA KHABAR"],
  ["مُحَمَّدٌ رَسُولُ اللهِ", "MUBTADA KHABAR MUDAF_ILAYH"],
  ["بَيْتُ الرَّجُلِ وَاسِعٌ", "MUBTADA MUDAF_ILAYH KHABAR"],
  ["قَلَمُ الطَّالِبِ جَدِيدٌ", "MUBTADA MUDAF_ILAYH KHABAR"],
  ["الطُّلَّابُ المُجْتَهِدُونَ نَاجِحُونَ", "MUBTADA NAAT KHABAR"],
  ["الوَلَدُ يَلْعَبُ", "MUBTADA FIL"],
  ["البِنْتُ تَقْرَأُ القُرْآنَ", "MUBTADA FIL MAFUL_BIH"],
  ["الأَوْلَادُ ذَهَبُوا إِلَى المَدْرَسَةِ", "MUBTADA FIL HARF_JARR MAJROOR"],
  ["الطَّالِبُ وَالمُعَلِّمُ حَاضِرَانِ", "MUBTADA HARF+MATUF KHABAR"],
  ["القَاضِي عَادِلٌ", "MUBTADA KHABAR"],
  ["المُسْتَشْفَى قَرِيبٌ", "MUBTADA KHABAR"],
  ["هَؤُلَاءِ طُلَّابٌ", "MUBTADA KHABAR"],
  ["ذَلِكَ الكِتَابُ مُفِيدٌ", "MUBTADA BADAL KHABAR"],
  ["أَبُوكَ كَرِيمٌ", "MUBTADA+MUDAF_ILAYH KHABAR"],
  ["الأُمُّ تُحِبُّ أَوْلَادَهَا", "MUBTADA FIL MAFUL_BIH+MUDAF_ILAYH"],
  ["هُمْ يَدْرُسُونَ", "MUBTADA FIL"],
  ["أَنْتُمْ طُلَّابٌ مُجْتَهِدُونَ", "MUBTADA KHABAR NAAT"],
  ["كُلُّ طَالِبٍ مُجْتَهِدٌ", "MUBTADA MUDAF_ILAYH KHABAR"],
  ["الحَمْدُ لِلَّهِ", "MUBTADA HARF_JARR+MAJROOR"],

  // --- idafa, na't, 'atf, badal
  ["جَاءَ الطَّالِبُ المُجْتَهِدُ", "FIL FAAIL NAAT"],
  ["رَأَيْتُ رَجُلًا كَرِيمًا", "FIL MAFUL_BIH NAAT"],
  ["مَرَرْتُ بِرَجُلٍ كَرِيمٍ", "FIL HARF_JARR+MAJROOR NAAT"],
  ["قَرَأْتُ كِتَابَ الأُسْتَاذِ", "FIL MAFUL_BIH MUDAF_ILAYH"],
  ["جَاءَ مُحَمَّدٌ وَعَلِيٌّ", "FIL FAAIL HARF+MATUF"],
  ["أَكَلْتُ الخُبْزَ وَاللَّحْمَ", "FIL MAFUL_BIH HARF+MATUF"],
  ["جَاءَ الطَّالِبُ ثُمَّ المُعَلِّمُ", "FIL FAAIL HARF MATUF"],
  ["اِشْتَرَيْتُ قَلَمًا أَوْ كِتَابًا", "FIL MAFUL_BIH HARF MATUF"],
  ["دَخَلْتُ غُرْفَةَ النَّوْمِ", "FIL MAFUL_BIH MUDAF_ILAYH"],
  ["بَابُ المَدْرَسَةِ الكَبِيرُ مُغْلَقٌ", "MUBTADA MUDAF_ILAYH NAAT KHABAR"],
  ["سَكَنْتُ فِي بَيْتٍ جَدِيدٍ", "FIL HARF_JARR MAJROOR NAAT"],
  ["هَذَا الرَّجُلُ طَبِيبٌ", "MUBTADA BADAL KHABAR"],
  ["صَلَّيْتُ فِي المَسْجِدِ الكَبِيرِ", "FIL HARF_JARR MAJROOR NAAT"],
  ["كَتَبْتُ بِقَلَمِ أَخِي", "FIL HARF_JARR+MAJROOR MUDAF_ILAYH+MUDAF_ILAYH"],

  // --- inna and its sisters
  ["إِنَّ اللهَ غَفُورٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["إِنَّ العِلْمَ نَافِعٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["لَعَلَّ الجَوَّ جَمِيلٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["لَيْتَ الشَّبَابَ عَائِدٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["كَأَنَّ القَمَرَ مِصْبَاحٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["إِنَّ المُسْلِمِينَ إِخْوَةٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["إِنَّكَ مُجْتَهِدٌ", "INNA+ISM_INNA KHABAR_INNA"],
  ["لَكِنَّ الطَّالِبَ غَائِبٌ", "INNA ISM_INNA KHABAR_INNA"],
  ["إِنَّ الطُّلَّابَ فِي الفَصْلِ", "INNA ISM_INNA HARF_JARR MAJROOR"],
  ["إِنَّ فِي البَيْتِ رَجُلًا", "INNA HARF_JARR MAJROOR ISM_INNA"],

  // --- kana and its sisters
  ["كَانَ الطَّالِبُ مُجْتَهِدًا", "KANA ISM_KANA KHABAR_KANA"],
  ["أَصْبَحَ الجَوُّ بَارِدًا", "KANA ISM_KANA KHABAR_KANA"],
  ["صَارَ المَاءُ ثَلْجًا", "KANA ISM_KANA KHABAR_KANA"],
  ["كَانَتِ السَّمَاءُ صَافِيَةً", "KANA ISM_KANA KHABAR_KANA"],
  ["لَيْسَ الكَسَلُ مَحْمُودًا", "KANA ISM_KANA KHABAR_KANA"],
  ["كَانُوا مُجْتَهِدِينَ", "KANA KHABAR_KANA"],
  ["مَا زَالَ المَطَرُ نَازِلًا", "HARF KANA ISM_KANA KHABAR_KANA"],
  ["كَانَ الوَلَدُ يَلْعَبُ", "KANA ISM_KANA FIL"],
  ["ظَلَّ الطَّالِبُ مُجْتَهِدًا", "KANA ISM_KANA KHABAR_KANA"],
  ["بَاتَ المَرِيضُ نَائِمًا", "KANA ISM_KANA KHABAR_KANA"],

  // --- negation
  ["لَمْ يَحْضُرِ الطَّالِبُ", "HARF FIL FAAIL"],
  ["لَمْ أَفْهَمِ الدَّرْسَ", "HARF FIL MAFUL_BIH"],
  ["لَنْ نَتْرُكَ الصَّلَاةَ", "HARF FIL MAFUL_BIH"],
  ["لَا تَلْعَبْ فِي الشَّارِعِ", "HARF FIL HARF_JARR MAJROOR"],
  ["لَا يَكْذِبُ المُؤْمِنُ", "HARF FIL FAAIL"],
  ["مَا حَضَرَ المُعَلِّمُ", "HARF FIL FAAIL"],
  ["لَا طَالِبَ غَائِبٌ", "HARF ISM_LA KHABAR_LA"],
  ["لَا إِلَهَ إِلَّا اللهُ", "HARF ISM_LA X X"],
  ["لَمْ يَكْتُبُوا الوَاجِبَ", "HARF FIL MAFUL_BIH"],
  ["لَنْ يَنْجَحَ الكَسُولُ", "HARF FIL FAAIL"],
  ["لَمْ يَنْسَ الطَّالِبُ الدَّرْسَ", "HARF FIL FAAIL MAFUL_BIH"],
  ["مَا الجَوُّ حَارًّا", "HARF ISM_KANA KHABAR_KANA"],

  // --- weak verbs, maqsur, manqus
  ["يَرْمِي الصَّيَّادُ السَّهْمَ", "FIL FAAIL MAFUL_BIH"],
  ["يَسْعَى الطَّالِبُ إِلَى النَّجَاحِ", "FIL FAAIL HARF_JARR MAJROOR"],
  ["رَمَى الوَلَدُ الكُرَةَ", "FIL FAAIL MAFUL_BIH"],
  ["جَاءَ الفَتَى", "FIL FAAIL"],
  ["مَرَرْتُ بِالقَاضِي", "FIL HARF_JARR+MAJROOR"],
  ["هَذَا هُدًى", "MUBTADA KHABAR"],
  ["رَأَيْتُ مُصْطَفَى", "FIL MAFUL_BIH"],
  ["المُحَامِي مَشْغُولٌ", "MUBTADA KHABAR"],
  ["دَعَوْتُ اللهَ", "FIL MAFUL_BIH"],
  ["يَدْعُونَ رَبَّهُمْ", "FIL MAFUL_BIH+MUDAF_ILAYH"],
  ["قُلِ الحَقَّ", "FIL MAFUL_BIH"],
  ["صُمْ رَمَضَانَ", "FIL MAFUL_BIH"],

  // --- attached pronouns and prepositions
  ["أَكْرَمَنِي المُعَلِّمُ", "FIL+MAFUL_BIH FAAIL"],
  ["كَتَبْتُهُ", "FIL+MAFUL_BIH"],
  ["رَأَيْتُهَا فِي السُّوقِ", "FIL+MAFUL_BIH HARF_JARR MAJROOR"],
  ["بَيْتُنَا كَبِيرٌ", "MUBTADA+MUDAF_ILAYH KHABAR"],
  ["قَلَمُكِ جَدِيدٌ", "MUBTADA+MUDAF_ILAYH KHABAR"],
  ["سَأَلْتُهُمْ عَنْهُ", "FIL+MAFUL_BIH HARF_JARR+MAJROOR"],
  ["نَظَرْتُ إِلَيْهِ", "FIL HARF_JARR+MAJROOR"],
  ["كِتَابُهَا مُفِيدٌ", "MUBTADA+MUDAF_ILAYH KHABAR"],
  ["فَهِمَهُ الطُّلَّابُ", "FIL+MAFUL_BIH FAAIL"],

  // --- hal, maf'ul mutlaq, tamyiz
  ["رَجَعَ الجُنْدِيُّ مُنْتَصِرًا", "FIL FAAIL HAL"],
  ["دَخَلَ الطَّالِبُ الفَصْلَ سَعِيدًا", "FIL FAAIL MAFUL_BIH HAL"],
  ["جَلَسَ الرَّجُلُ حَزِينًا", "FIL FAAIL HAL"],
  ["اسْتَغْفَرْتُ رَبِّي اسْتِغْفَارًا", "FIL MAFUL_BIH+MUDAF_ILAYH MAFUL_MUTLAQ"],
  ["انْطَلَقَ القِطَارُ انْطِلَاقًا سَرِيعًا", "FIL FAAIL MAFUL_MUTLAQ NAAT"],
  ["فَرِحَ الطِّفْلُ فَرَحًا شَدِيدًا", "FIL FAAIL MAFUL_MUTLAQ NAAT"],
  ["تَعَلَّمْتُ العَرَبِيَّةَ تَعَلُّمًا", "FIL MAFUL_BIH MAFUL_MUTLAQ"],
  ["زَيْدٌ أَكْبَرُ سِنًّا", "MUBTADA KHABAR TAMYIZ"],
  ["الذَّهَبُ أَغْلَى ثَمَنًا", "MUBTADA KHABAR TAMYIZ"],
  ["فِي الفَصْلِ ثَلَاثُونَ طَالِبًا", "HARF_JARR MAJROOR MUBTADA TAMYIZ"],
  ["قَرَأْتُ أَرْبَعِينَ صَفْحَةً", "FIL MAFUL_BIH TAMYIZ"],

  // --- relative clauses
  ["نَجَحَ الَّذِي اجْتَهَدَ", "FIL FAAIL FIL"],
  ["أَحْتَرِمُ الَّذِينَ يَصْدُقُونَ", "FIL MAFUL_BIH FIL"],
  ["جَاءَتِ الطَّالِبَةُ الَّتِي فَازَتْ", "FIL FAAIL NAAT FIL"],
  ["رَأَيْتُ الرَّجُلَ الَّذِي فِي السُّوقِ", "FIL MAFUL_BIH NAAT HARF_JARR MAJROOR"],
  ["الَّذِينَ آمَنُوا فَازُوا", "MUBTADA FIL FIL"],
  ["سَلَّمْتُ عَلَى الَّذِي حَضَرَ", "FIL HARF_JARR MAJROOR FIL"],
  ["المُعَلِّمَاتُ اللَّاتِي حَضَرْنَ مُجْتَهِدَاتٌ", "MUBTADA NAAT FIL KHABAR"],
  ["الطَّالِبُ الَّذِي نَجَحَ مَسْرُورٌ", "MUBTADA NAAT FIL KHABAR"],
  ["هَذَا هُوَ الكِتَابُ الَّذِي قَرَأْتُهُ", "MUBTADA X KHABAR NAAT FIL+MAFUL_BIH"],

  // --- conditionals and أَنْ + verb
  ["إِنْ تَصْدُقْ تَنْجُ", "HARF FIL FIL"],
  ["مَنْ يَزْرَعْ يَحْصُدْ", "MUBTADA FIL FIL"],
  ["إِنْ تَقْرَأْ تَتَعَلَّمْ", "HARF FIL FIL"],
  ["مَنْ صَبَرَ ظَفِرَ", "MUBTADA FIL FIL"],
  ["إِنْ جَاءَ زَيْدٌ أَكْرَمْتُهُ", "HARF FIL FAAIL FIL+MAFUL_BIH"],
  ["أُحِبُّ أَنْ أَقْرَأَ", "FIL HARF FIL"],
  ["نُرِيدُ أَنْ نَتَعَلَّمَ العَرَبِيَّةَ", "FIL HARF FIL MAFUL_BIH"],
  ["يُحِبُّ المُسْلِمُ أَنْ يُصَلِّيَ", "FIL FAAIL HARF FIL"],

  // --- adverbs (ظرف = مفعول فيه) and two-object verbs
  ["يَجْلِسُ الطُّلَّابُ أَمَامَ المُعَلِّمِ", "FIL FAAIL MAFUL_FIH MUDAF_ILAYH"],
  ["الكِتَابُ فَوْقَ المَكْتَبِ", "MUBTADA MAFUL_FIH MUDAF_ILAYH"],
  ["عِنْدِي سَيَّارَةٌ", "MAFUL_FIH+MUDAF_ILAYH MUBTADA"],
  ["ذَهَبْتُ مَعَ صَدِيقِي", "FIL MAFUL_FIH MUDAF_ILAYH+MUDAF_ILAYH"],
  ["وَصَلْتُ قَبْلَ الظُّهْرِ", "FIL MAFUL_FIH MUDAF_ILAYH"],
  ["صُمْتُ يَوْمَ الخَمِيسِ", "FIL MAFUL_FIH MUDAF_ILAYH"],
  ["ظَنَنْتُ الطَّالِبَ مُجْتَهِدًا", "FIL MAFUL_BIH MAFUL_BIH"],
  ["أَعْطَيْتُ الفَقِيرَ دِرْهَمًا", "FIL MAFUL_BIH MAFUL_BIH"],
  ["جَعَلَ اللهُ اللَّيْلَ سَكَنًا", "FIL FAAIL MAFUL_BIH MAFUL_BIH"],

  // --- attached pronouns and coordinated clauses (from live testing)
  ["ضَرَبَهُ الرَّجُلُ", "FIL+MAFUL_BIH FAAIL"],
  ["قَرَأَ الطَّالِبُ الكِتَابَ وَفَهِمَهُ", "FIL FAAIL MAFUL_BIH HARF+FIL+MAFUL_BIH"],
  ["كِتَابِي جَدِيدٌ", "MUBTADA+MUDAF_ILAYH KHABAR"],
  ["وَجَدَ الوَلَدُ القَلَمَ فِي حَقِيبَتِهِ", "FIL FAAIL MAFUL_BIH HARF_JARR MAJROOR+MUDAF_ILAYH"],
  ["ذَهَبَ الوَلَدُ ثُمَّ رَجَعَ", "FIL FAAIL HARF FIL"],
  ["جَلَسَ الطَّالِبُ وَكَتَبَ الدَّرْسَ", "FIL FAAIL HARF+FIL MAFUL_BIH"],

  // --- outside the parser's coverage: the right answer is to decline
  ["هَلْ ذَهَبْتَ إِلَى المَدْرَسَةِ", "HARF FIL HARF_JARR MAJROOR"],
  ["يَا طَالِبُ اجْتَهِدْ", "X X FIL"],
  ["لَقَدْ نَجَحَ الطَّالِبُ", "HARF FIL FAAIL"],
  ["ذَهَبْتُ إِلَى مَكَّةَ", "FIL HARF_JARR MAJROOR"],
  ["مَرَرْتُ بِمَسَاجِدَ كَثِيرَةٍ", "FIL HARF_JARR+MAJROOR NAAT"],
  ["قَالَ المُعَلِّمُ إِنَّ الدَّرْسَ سَهْلٌ", "FIL FAAIL INNA ISM_INNA KHABAR_INNA"],
  ["إِذَا جَاءَ الشِّتَاءُ بَرَدَ الجَوُّ", "MAFUL_FIH FIL FAAIL FIL FAAIL"],
  ["أَيْنَ الكِتَابُ", "X MUBTADA"],
  ["مَا أَجْمَلَ السَّمَاءَ", "MUBTADA FIL MAFUL_BIH"],
  ["سُبْحَانَ اللهِ", "MAFUL_MUTLAQ MUDAF_ILAYH"],
  ["جَاءَ الطُّلَّابُ كُلُّهُمْ", "FIL FAAIL X+MUDAF_ILAYH"],
  ["جِئْتُ لِأَتَعَلَّمَ", "FIL HARF+FIL"],
  ["بِسْمِ اللهِ", "HARF_JARR+MAJROOR MUDAF_ILAYH"],
  ["عِنْدَكَ كِتَابٌ", "MAFUL_FIH+MUDAF_ILAYH MUBTADA"],
];
